site_name: Cryptography Primer
nav:
- Home: index2.md
- Encryption: encryption.md
- Hashing: hashing.md
- Signing: signing.md
- PKI: pki.md
- Systems: systems.md
- History: history.md
- Glossary: glossary.md

theme:
  name: material
  favicon: images/favicon.svg
  logo: images/favicon.svg
  icon:
    admonition:
      recommendation: octicons/info-16
  features:
    - navigation.tabs
  custom_dir: overrides

copyright: Copyright &copy; 2022 Daniel Albuschat <a href="/imprint/">(Imprint)</a>

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dalbuschat
    - icon: fontawesome/brands/github
      link: https://github.com/daniel-kun/cryptography-primer.info/
    - icon: fontawesome/brands/xing
      link: https://www.xing.com/profile/Daniel_Albuschat/cv

markdown_extensions:
  - footnotes
  - admonition
  - abbr
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css
